# -*- coding: utf-8 -*-
"""electricity prediction updation in code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gP2wOLyXn-W54yWTy1J55NqxhZp6eEeF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tabulate import tabulate
import matplotlib.ticker as mticker

# Load dataset
df = pd.read_csv('Electricity_dataset(4cities).csv')

# Display original dataset
def show_original_data():
    print("Original Dataset:")
    print(tabulate(df.head(), headers='keys', tablefmt='grid'))

# City-wise tariff rate
def city_wise_tariff():
    city_tariff = df.groupby('City')['TariffRate'].mean()
    print("\nCity-wise Tariff Rate:")
    print(tabulate(city_tariff.reset_index(), headers='keys', tablefmt='grid'))

    plt.figure(figsize=(8,5))
    city_tariff.plot(kind='bar', color='skyblue')
    plt.title('City-wise Average Tariff Rate')
    plt.xlabel('City')
    plt.ylabel('Tariff Rate')
    plt.show()

# Average electricity bill per month (separate graph per city)
def avg_bill_per_month():
    monthly_bill = df.groupby(['City', 'Months'])['ElectricityBill'].mean().unstack()
    print("\nAverage Electricity Bill per Month:")
    print(tabulate(monthly_bill, headers='keys', tablefmt='grid'))

    monthly_bill.T.plot(kind='line', figsize=(10,6), marker='o')
    plt.title('Average Electricity Bill per Month (City-wise)')
    plt.xlabel('Month')
    plt.ylabel('Electricity Bill')
    plt.legend(title='City')
    plt.show()

# Average monthly consumption per city
def avg_monthly_consumption():
    consumption = df.groupby('City')['MonthlyHours'].mean()
    print("\nAverage Monthly Consumption per City:")
    print(tabulate(consumption.reset_index(), headers='keys', tablefmt='grid'))

    consumption.plot(kind='bar', color='orange', figsize=(8,5))
    plt.title('Average Monthly Consumption per City')
    plt.xlabel('City')
    plt.ylabel('Consumption (kWh)')
    plt.show()


# Total monthly hours per company with split visualization
def total_monthly_hours_per_company():
    total_hours = df.groupby(['Company', 'Months'])['MonthlyHours'].sum().unstack()
    print("\nTotal Monthly Hours per Company:")
    print(tabulate(total_hours, headers='keys', tablefmt='grid'))

    companies = total_hours.index
    num_companies = len(companies)

    # Dynamically determine grid size
    rows = (num_companies // 2) + (num_companies % 2)
    cols = min(2, num_companies)

    fig, axes = plt.subplots(rows, cols, figsize=(12, 5 * rows))
    axes = axes.flatten() if num_companies > 1 else [axes]

    for i, company in enumerate(companies):
        total_hours.loc[company].plot(kind='line', marker='s', ax=axes[i])
        axes[i].set_title(f'Total Monthly Usage Hours: {company}')
        axes[i].set_xlabel('Month')
        axes[i].set_ylabel('Total Usage Hours')

    # Hide any unused subplots
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()

def total_revenue():
    revenue_company = df.groupby('Company')['ElectricityBill'].sum()
    revenue_city = df.groupby('City')['ElectricityBill'].sum()

    # Convert values to formatted rupees
    revenue_company_formatted = revenue_company.apply(lambda x: f"₹{x:,.2f}")
    revenue_city_formatted = revenue_city.apply(lambda x: f"₹{x:,.2f}")

    print("\nTotal Revenue per Company:")
    print(tabulate(revenue_company_formatted.reset_index(), headers=['Company', 'Total Revenue (₹)'], tablefmt='grid'))
    print("\nTotal Revenue per City:")
    print(tabulate(revenue_city_formatted.reset_index(), headers=['City', 'Total Revenue (₹)'], tablefmt='grid'))

    fig, ax = plt.subplots(1, 2, figsize=(12, 5))

    revenue_company.plot(kind='bar', ax=ax[0], color='green')
    ax[0].set_title('Total Revenue per Company')
    ax[0].set_ylabel('Revenue (₹)')
    ax[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₹{x:,.0f}'))

    revenue_city.plot(kind='bar', ax=ax[1], color='red')
    ax[1].set_title('Total Revenue per City')
    ax[1].set_ylabel('Revenue (₹)')
    ax[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₹{x:,.0f}'))

    plt.subplots_adjust(bottom=0.2, top=0.9)  # Adjust margins manually

    plt.show()


# Average tariff rate by companies
def avg_tariff_by_company():
    avg_tariff = df.groupby('Company')['TariffRate'].mean()
    print("\nAverage Tariff Rate per Company:")
    print(tabulate(avg_tariff.reset_index(), headers='keys', tablefmt='grid'))

    avg_tariff.plot(kind='bar', color='purple', figsize=(8,5))
    plt.title('Average Tariff Rate per Company')
    plt.xlabel('Company')
    plt.ylabel('Tariff Rate')
    plt.show()

# Total appliances usage
def total_appliance_usage():
    appliance_usage = df[['Fan_hours', 'Refrigerator_hours', 'AirConditioner_hours', 'Monitor_hours','Television_hours']].sum()
    print("\nTotal Appliance Usage:")
    print(tabulate(appliance_usage.reset_index(), headers=['Appliance', 'Usage Hours'], tablefmt='grid'))

    appliance_usage.plot(kind='bar', color='brown', figsize=(8,5))
    plt.title('Total Appliance Usage (Hours)')
    plt.xlabel('Appliance')
    plt.ylabel('Total Usage Hours')
    plt.show()


# Improved Automated Electricity Bill Prediction City-wise from Dataset

def automated_electricity_bill_prediction():
    # Required numeric columns
    appliance_cols = [
        'Fan_hours',
        'Refrigerator_hours',
        'AirConditioner_hours',
        'Monitor_hours',
        'Television_hours'
    ]

    required_cols = appliance_cols + ['TariffRate', 'City']

    # Check if all required columns exist
    missing_cols = [col for col in required_cols if col not in df.columns]

    if missing_cols:
        print(f"Error: Missing columns in dataset - {missing_cols}")
        return

    # Convert numeric columns safely
    numeric_cols = appliance_cols + ['TariffRate']

    df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

    # Fill missing numeric values with median
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

    # Calculate city-wise average appliance usage
    city_avg_usage = df.groupby('City')[appliance_cols].mean()

    # Calculate city-wise average tariff rate
    city_avg_tariff = df.groupby('City')['TariffRate'].mean()

    # Convert average daily appliance usage to monthly kWh city-wise
    city_monthly_kwh = (
        (city_avg_usage['Fan_hours'] * 30 * 0.0625) +
        (city_avg_usage['Refrigerator_hours'] * 30 * 0.150) +
        (city_avg_usage['AirConditioner_hours'] * 30 * 1.5) +
        (city_avg_usage['Monitor_hours'] * 30 * 0.0225) +
        (city_avg_usage['Television_hours'] * 30 * 0.125)
    )

    # Calculate predicted monthly bill city-wise
    predicted_bills = city_monthly_kwh * city_avg_tariff

    # Create final result table
    result = pd.DataFrame({
        'City': predicted_bills.index,
        'Average Monthly Units (kWh)': city_monthly_kwh.values,
        'Average Tariff Rate (₹/kWh)': city_avg_tariff.values,
        'Estimated Monthly Bill (₹)': predicted_bills.values
    })

    # Round values for better display
    result['Average Monthly Units (kWh)'] = result['Average Monthly Units (kWh)'].round(2)
    result['Average Tariff Rate (₹/kWh)'] = result['Average Tariff Rate (₹/kWh)'].round(2)
    result['Estimated Monthly Bill (₹)'] = result['Estimated Monthly Bill (₹)'].round(2)

    print("\n🔹 Improved City-wise Predicted Monthly Electricity Bill:")
    print(tabulate(result, headers='keys', tablefmt='grid', showindex=False))

    # Visualization
    plt.figure(figsize=(10, 5))
    sns.barplot(
        x='City',
        y='Estimated Monthly Bill (₹)',
        data=result,
        hue='City',
        palette='coolwarm',
        legend=False
    )

    plt.title('Improved City-wise Predicted Monthly Electricity Bill')
    plt.xlabel('City')
    plt.ylabel('Estimated Monthly Bill (₹)')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# User Input Electricity Usage Analysis and Bill Prediction
# User Input Electricity Usage Analysis and Bill Prediction

# Convert appliance usage hours into kWh
def convert_to_kwh(hours, wattage):
    return (hours * wattage) / 1000


# Function to get valid float input
def get_valid_float_input(prompt):
    while True:
        try:
            value = float(input(prompt).strip())

            if value < 0:
                print("Value cannot be negative. Please enter a positive value.")
                continue

            return value

        except ValueError:
            print("Invalid input! Please enter a numeric value.")


# User Input Electricity Usage Analysis and Bill Prediction
def user_input_usage_analysis():

    # Preloaded appliances with wattage
    preloaded_appliances = {
        "Fan": 62.5,
        "Fridge": 150,
        "AC": 1500,
        "Monitor": 22.5,
        "TV": 125
    }

    selected_appliances = {}

    # City selection
    cities = df['City'].unique()

    print("\nAvailable Cities:")
    for i, city in enumerate(cities, 1):
        print(f"{i}. {city}")

    print(f"{len(cities) + 1}. Enter a custom tariff rate")

    while True:
        try:
            choice = int(input("Select an option: "))

            if choice == len(cities) + 1:
                tariff_rate = get_valid_float_input("Enter your custom tariff rate (₹ per kWh): ")
                selected_city = "Custom Tariff"
                break

            elif 1 <= choice <= len(cities):
                selected_city = cities[choice - 1]
                tariff_rate = df[df['City'] == selected_city]['TariffRate'].mean()
                print(f"Selected City: {selected_city}, Tariff Rate: ₹{tariff_rate:.2f} per kWh")
                break

            else:
                print("Invalid choice! Please select a valid city option.")

        except ValueError:
            print("Invalid input! Please enter a number.")

    # Ask user which preloaded appliances they use
    print("\nSelect Appliances You Use:")

    for appliance, wattage in preloaded_appliances.items():
        use_appliance = input(f"Do you use {appliance}? (yes/no): ").strip().lower()

        if use_appliance == "yes":
            selected_appliances[appliance] = wattage
        else:
            print(f"{appliance} removed from calculation.")

    # Add custom appliances
    add_custom = input("\nDo you want to add any custom appliance? (yes/no): ").strip().lower()

    if add_custom == "yes":
        while True:
            appliance_name = input("Enter custom appliance name: ").strip().title()
            wattage = get_valid_float_input(f"Enter wattage for {appliance_name}: ")

            selected_appliances[appliance_name] = wattage
            print(f"{appliance_name} added with {wattage} W.")

            more = input("Do you want to add another custom appliance? (yes/no): ").strip().lower()

            if more != "yes":
                break

    # If no appliance selected
    if len(selected_appliances) == 0:
        print("No appliances selected. Cannot calculate electricity usage.")
        return

    print("\nFinal Selected Appliances:")
    for appliance, wattage in selected_appliances.items():
        print(f"- {appliance} ({wattage} W)")

    print("\nEnter 7-day usage hours in one line.")
    print("Example: 5 6 5 7 6 5 4")

    appliance_usage = {}

    # Take 7-day input in one line for each selected appliance
    for appliance in selected_appliances:
        while True:
            try:
                usage_input = input(f"Enter {appliance} usage for 7 days: ").strip().split()

                if len(usage_input) != 7:
                    print("Please enter exactly 7 values.")
                    continue

                usage_values = [float(value) for value in usage_input]

                if any(value < 0 for value in usage_values):
                    print("Usage hours cannot be negative.")
                    continue

                appliance_usage[appliance] = usage_values
                break

            except ValueError:
                print("Invalid input! Please enter numeric values only.")

    # Calculate daily kWh
    daily_kwh = []

    for day in range(7):
        total_kwh = 0

        for appliance, wattage in selected_appliances.items():
            hours = appliance_usage[appliance][day]
            total_kwh += convert_to_kwh(hours, wattage)

        daily_kwh.append(total_kwh)

    avg_daily_kwh = sum(daily_kwh) / 7
    monthly_kwh = avg_daily_kwh * 30
    estimated_bill = monthly_kwh * tariff_rate

    # Display daily usage table
    print("\n🔹 Electricity Usage Trends (kWh per day):")

    print(tabulate(
        [[f"Day {i + 1}", round(daily_kwh[i], 2)] for i in range(7)],
        headers=['Day', 'kWh Used'],
        tablefmt='grid'
    ))

    print(f"\nSelected City / Tariff Type: {selected_city}")
    print(f"Average Daily Consumption: {avg_daily_kwh:.2f} kWh")
    print(f"Estimated Monthly Consumption: {monthly_kwh:.2f} kWh")
    print(f"Estimated Monthly Electricity Bill: ₹{estimated_bill:.2f}")

    # Visualization
    plt.figure(figsize=(8, 5))
    plt.plot(range(1, 8), daily_kwh, marker='o', linestyle='-')
    plt.title('Electricity Usage Trends for 7 Days')
    plt.xlabel('Day')
    plt.ylabel('Electricity Consumption (kWh)')
    plt.xticks(range(1, 8))
    plt.grid()
    plt.show()


# Run all functions
show_original_data()
city_wise_tariff()
avg_bill_per_month()
avg_monthly_consumption()
total_monthly_hours_per_company()
total_revenue()
avg_tariff_by_company()
total_appliance_usage()
automated_electricity_bill_prediction()
user_input_usage_analysis()